Fixed Background Image Visibility Issue on Profile Card (#31)
BeehiveCommunity/Frontend_Mentor pull request #375
Opened 2024-10-15 03:30 UTC by syedfardeenjeelani

## What does this PR do?

This PR fixes the issue where the background images (`bg-top` and `bg-bottom`) on the profile card disappear or become less visible on smaller screens. The issue is addressed by resizing the background images using `vw` units and adjusting their position to ensure visibility across different viewport sizes.

Fixes #31

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

1. Open the profile card on various screen sizes (desktop, tablet, mobile).
2. Verify that the background images remain visible and proportionate as the screen size reduces.
3. Check for any visual regressions on larger screens.

- [X] Test A: Check visibility of `bg-top` and `bg-bottom` images on a mobile screen (max-width: 375px).
- [X] Test B: Validate responsiveness and layout on a tablet (max-width: 768px).

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-10-15 12:24 UTC, beRajeevKumar requested changes
@syedfardeenjeelani, Now background images are not working on mobile devices, so make some changes please then I will merge your branch.

2024-10-15 12:32 UTC, syedfardeenjeelani commented
> @syedfardeenjeelani, Now background images are not working on mobile devices, so make some changes please then I will merge your branch.

sure

2024-10-15 13:16 UTC, syedfardeenjeelani commented
@beRajeevKumar  kindly review my pr

2024-10-18 16:12 UTC, syedfardeenjeelani commented
@beRajeevKumar please review my pr

2025-01-08 22:43 UTC, closed without merging